apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: hashicorp/vault
    helm:
      values: |
        injector:
          enabled: false
    repoURL: https://helm.releases.hashicorp.com 
    targetRevision: 0.20.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
